import './globals.css';
import type { AppProps } from 'next/app';
import { Providers } from '../redux/providers';
// import { wrapper } from '../redux/store';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
